# **Approach 1:** Group products using existing fields

## Tasks 1 & 2: Match identical/variant products

In this approach, we assume that products with identical `brand`, `color`, `category`, `'name` and `description` are identical products, so we perform a grouping based on these attributes.

In [1]:
!pip install -qq torchvision
!pip install -qq hdbscan
!pip install -qq rapidfuzz

In [2]:
# Import libraries
import numpy as np
import pandas as pd
import json
import os
from collections import Counter, defaultdict
from itertools import count, product
from tqdm import tqdm

import matplotlib.pyplot as plt
from IPython.display import display, HTML

import requests
from io import BytesIO
from PIL import Image

from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
import hdbscan
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder, normalize

from sklearn.metrics import silhouette_score, pair_confusion_matrix
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances

import torch
import torchvision.models as models
import torchvision.transforms as transforms

### Function to visualize products

In [3]:
# Function to visualize clusters as HTML with an optional max_products limit
def show_clusters_as_html(df, cluster_ids, max_products=None):
    for cluster_id in cluster_ids:
        cluster_df = df[df['cluster_label'] == cluster_id]
        if cluster_df.empty:
            print(f"Cluster {cluster_id} is empty!")
            continue

        if max_products is not None:
            cluster_df = cluster_df.head(max_products)

        html = f"<h3 style='margin-top:20px'>Cluster {cluster_id} ({len(cluster_df)} items)</h3>"
        html += "<div style='display:flex;flex-wrap:wrap'>"

        for _, row in cluster_df.iterrows():
            name = row.get('product_name', '')
            
            # Choose the best available image
            for col in [
                'mainImage.original_url',
                'secondary_image_1.original_url',
                'secondary_image_2.original_url',
                'secondary_image_3.original_url'
            ]:
                img = row.get(col, '')
                if isinstance(img, str) and img.startswith('http'):
                    break
            else:
                img = ''
            
            html += f"""
                <div style='margin:10px;text-align:center'>
                    <img src='{img}' width='120' style='border-radius:8px'><br>
                    <div style='max-width:120px;font-size:12px'>{name}</div>
                </div>
            """
        html += "</div>"
        display(HTML(html))

# **EDA & preprocessing**

In [4]:
# Read data
df = pd.read_json('sneakers_sample_19062025.txt', lines=False)

print(df.head())

                                                data  \
0  {'EAN': [], 'size': '44', 'brand': 'ASICS', 'c...
1  {'EAN': [], 'size': '44', 'brand': 'VANS', 'co...
2  {'EAN': [], 'size': '44.5', 'brand': 'ADIDAS',...
3  {'EAN': [], 'size': '42', 'brand': 'NIKE', 'co...
4  {'EAN': [], 'size': '11/EU 46', 'brand': 'PUMA...

                      mirakl_product_id             creation_date  \
0  d96975c5-0bea-41f6-a4a8-fdac53f374f3  2024-01-09T12:09:20.568Z
1  6f302b78-9a86-484e-894f-bb39220931a3  2023-11-09T13:08:33.276Z
2  70006973-aa9f-4176-9f38-0ba2c5a1b06f  2025-03-29T08:43:47.421Z
3  6b010b1d-7475-44dc-ad56-502769d2e742  2024-01-04T12:29:59.343Z
4  cf04d217-bfd6-4743-ae4b-bc98712959ca  2025-02-13T14:31:57.524Z

                update_date                           product_sku  \
0  2024-11-06T13:03:01.469Z  d96975c5-0bea-41f6-a4a8-fdac53f374f3
1  2025-02-12T12:21:44.083Z  6f302b78-9a86-484e-894f-bb39220931a3
2  2025-03-30T21:07:23.464Z  70006973-aa9f-4176-9f38-0ba2c5a1b06f
3  2024-11-06T13:00:53.470Z  6b010b1d-7475-44dc-ad56-502769d2e742
4  2025-03-01T00:03:24.205Z  cf04d217-bfd6-4743-ae4b-bc98712959ca

                                     validation             synchronization  \
0  {'status': 'VALID', 'validation_errors': []}  {'status': 'SYNCHRONIZED'}
1  {'status': 'VALID', 'validation_errors': []}  {'status': 'SYNCHRONIZED'}
2  {'status': 'VALID', 'validation_errors': []}  {'status': 'SYNCHRONIZED'}
3  {'status': 'VALID', 'validation_errors': []}  {'status': 'SYNCHRONIZED'}
4  {'status': 'VALID', 'validation_errors': []}  {'status': 'SYNCHRONIZED'}

  catalogs product_urls                                            sources  \
0       []           []  [{'provider_code': '2077', 'provider_sku': '10...
1       []           []  [{'provider_code': '2002', 'provider_sku': 'VN...
2       []           []  [{'provider_code': '2167', 'provider_sku': 'IH...
3       []           []  [{'provider_code': '2077', 'provider_sku': 'CT...
4       []           []  [{'provider_code': '3390', 'provider_sku': '46...

                               selling_authorization  \
0  {'restricted': False, 'authorized_selling_shop...
1  {'restricted': False, 'authorized_selling_shop...
2  {'restricted': False, 'authorized_selling_shop...
3  {'restricted': False, 'authorized_selling_shop...
4  {'restricted': False, 'authorized_selling_shop...

                                         data_origin
0  {'name [en_GB]': {'origin': 'PROVIDER', 'provi...
1  {'name [en_GB]': {'origin': 'PROVIDER', 'provi...
2  {'name [en_GB]': {'origin': 'PROVIDER', 'provi...
3  {'name [en_GB]': {'origin': 'PROVIDER', 'provi...
4  {'name [en_GB]': {'origin': 'PROVIDER', 'provi...

In [5]:
df.head()

,data,mirakl_product_id,creation_date,update_date,product_sku,validation,synchronization,catalogs,product_urls,sources,selling_authorization,data_origin
0,"{'EAN': [], 'size': '44', 'brand': 'ASICS', 'c...",d96975c5-0bea-41f6-a4a8-fdac53f374f3,2024-01-09T12:09:20.568Z,2024-11-06T13:03:01.469Z,d96975c5-0bea-41f6-a4a8-fdac53f374f3,"{'status': 'VALID', 'validation_errors': []}",{'status': 'SYNCHRONIZED'},[],[],"[{'provider_code': '2077', 'provider_sku': '10...","{'restricted': False, 'authorized_selling_shop...","{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
1,"{'EAN': [], 'size': '44', 'brand': 'VANS', 'co...",6f302b78-9a86-484e-894f-bb39220931a3,2023-11-09T13:08:33.276Z,2025-02-12T12:21:44.083Z,6f302b78-9a86-484e-894f-bb39220931a3,"{'status': 'VALID', 'validation_errors': []}",{'status': 'SYNCHRONIZED'},[],[],"[{'provider_code': '2002', 'provider_sku': 'VN...","{'restricted': False, 'authorized_selling_shop...","{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
2,"{'EAN': [], 'size': '44.5', 'brand': 'ADIDAS',...",70006973-aa9f-4176-9f38-0ba2c5a1b06f,2025-03-29T08:43:47.421Z,2025-03-30T21:07:23.464Z,70006973-aa9f-4176-9f38-0ba2c5a1b06f,"{'status': 'VALID', 'validation_errors': []}",{'status': 'SYNCHRONIZED'},[],[],"[{'provider_code': '2167', 'provider_sku': 'IH...","{'restricted': False, 'authorized_selling_shop...","{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
3,"{'EAN': [], 'size': '42', 'brand': 'NIKE', 'co...",6b010b1d-7475-44dc-ad56-502769d2e742,2024-01-04T12:29:59.343Z,2024-11-06T13:00:53.470Z,6b010b1d-7475-44dc-ad56-502769d2e742,"{'status': 'VALID', 'validation_errors': []}",{'status': 'SYNCHRONIZED'},[],[],"[{'provider_code': '2077', 'provider_sku': 'CT...","{'restricted': False, 'authorized_selling_shop...","{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
4,"{'EAN': [], 'size': '11/EU 46', 'brand': 'PUMA...",cf04d217-bfd6-4743-ae4b-bc98712959ca,2025-02-13T14:31:57.524Z,2025-03-01T00:03:24.205Z,cf04d217-bfd6-4743-ae4b-bc98712959ca,"{'status': 'VALID', 'validation_errors': []}",{'status': 'SYNCHRONIZED'},[],[],"[{'provider_code': '3390', 'provider_sku': '46...","{'restricted': False, 'authorized_selling_shop...","{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."

### Create separate dataframes

In [6]:
# Load the JSON file
with open('sneakers_sample_19062025.txt', 'r', encoding='utf-8') as f:    # added encoding = utf8 otherwise: decoding error
    raw_data = json.load(f)

# Create separate dataframes
meta_rows = []
data_rows = []
sources_rows = []

# Exclude some fields that are not necessary for our tasks
exclude_fields = {
    'creation_date', 'update_date',
    'validation', 'synchronization',
    'catalogs', 'selling_authorization', "product_urls"
}

for entry in raw_data:
    # Top-level fields
    meta = {
        key: entry[key] for key in entry
        if key not in exclude_fields and key not in ['data', 'sources']
    }
    meta_rows.append(meta)
    
    # Extract nested fields (if they exist)
    if 'data' in entry:
        data_rows.append(entry['data'])
    if 'sources' in entry and isinstance(entry['sources'], list):
        for source in entry['sources']:
            # Optionally, attach product ID to track back
            source['mirakl_product_id'] = entry.get('mirakl_product_id')
            sources_rows.append(source)

# Convert all parts to DataFrames
df_meta = pd.DataFrame(meta_rows)
df_data = pd.json_normalize(data_rows)
df_sources = pd.DataFrame(sources_rows)

# Preview
print("Meta columns:", df_meta.columns.tolist())
print("Data columns:", df_data.columns.tolist())
print("Sources sample:", df_sources.head())

Meta columns: ['mirakl_product_id', 'product_sku', 'data_origin']
Data columns: ['EAN', 'size', 'brand', 'color', 'category', 'returnable', 'name [el_CY]', 'name [en_GB]', 'updateOnDelta', 'refinementColor', 'variantGroupCode', 'jiniusSkuMatchCode', 'shortDescription [el_CY]', 'shortDescription [en_GB]', 'mainImage.source', 'mainImage.original_url', 'secondary_image_1.source', 'secondary_image_1.original_url', 'secondary_image_2.source', 'secondary_image_2.original_url', 'secondary_image_3.source', 'secondary_image_3.original_url', 'longDescription [en_GB]', 'longDescription [el_CY]', 'shoeType', 'shoeShape', 'fashionMaterial', 'shoeWidth', 'heelHeight', 'name', 'heelType', 'longDescription', 'shortDescription']
Sources sample:   provider_code                               provider_sku  \
0          2077        1071A091-101--EUM-18--WHITE / BLACK
1          2002                   VN0A3MTJT2J1--417--BLACK
2          2167                                IH6003-44.5
3          2077  CT2927-100--USAM-09--WHITE / BLACK / VOLT
4          3390                          468781-1870785842

                      mirakl_product_id
0  d96975c5-0bea-41f6-a4a8-fdac53f374f3
1  6f302b78-9a86-484e-894f-bb39220931a3
2  70006973-aa9f-4176-9f38-0ba2c5a1b06f
3  6b010b1d-7475-44dc-ad56-502769d2e742
4  cf04d217-bfd6-4743-ae4b-bc98712959ca

In [7]:
df_data

,EAN,size,brand,color,category,returnable,name [el_CY],name [en_GB],updateOnDelta,refinementColor,...,longDescription [el_CY],shoeType,shoeShape,fashionMaterial,shoeWidth,heelHeight,name,heelType,longDescription,shortDescription
0,[],44,ASICS,White / Black,FaMeShSneakers,true,Gel-rocket 11 mens volleyball/indoor shoes,Gel-rocket 11 mens volleyball/indoor shoes,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[],44,VANS,Black,FaMeShSneakers,true,Mens filmore suede,Mens filmore suede,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[],44.5,ADIDAS,NaN,FaMeShSneakers,true,Ih6003,Adidas response,NaN,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],42,NIKE,White / Black / Volt,FaMeShSneakers,true,React vision worldwide mens,React vision worldwide mens,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[],11/EU 46,PUMA,Black/white,FaMeShSneakers,true,Puma men's x-ray 3 sd,Puma men's x-ray 3 sd,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5818,[],37,BUFFALO,White / Silver / Black,FaWoShSneakers,true,Triple hollow sneakers,Triple hollow sneakers,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5819,[],39,ADIDAS ORIGINALS,White,FaWoShSneakers,true,Adidas sambae w,Adidas sambae w,NaN,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5820,[],41,GUESS,White,FaWoShSneakers,true,Elbina sneakers,Elbina sneakers,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5821,[],36.5,NEW BALANCE,Cloud White / Burgundy,FaWoShSneakers,true,327 sportstyle sneakers,327 sportstyle sneakers,None,miscellaneous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5822,[],37,NEW BALANCE,Cloud White / Burgundy,FaWoShSneakers,true,New balance 327 sportstyle sneakers,New balance 327 sportstyle sneakers,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_meta

,mirakl_product_id,product_sku,data_origin
0,d96975c5-0bea-41f6-a4a8-fdac53f374f3,d96975c5-0bea-41f6-a4a8-fdac53f374f3,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
1,6f302b78-9a86-484e-894f-bb39220931a3,6f302b78-9a86-484e-894f-bb39220931a3,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
2,70006973-aa9f-4176-9f38-0ba2c5a1b06f,70006973-aa9f-4176-9f38-0ba2c5a1b06f,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
3,6b010b1d-7475-44dc-ad56-502769d2e742,6b010b1d-7475-44dc-ad56-502769d2e742,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
4,cf04d217-bfd6-4743-ae4b-bc98712959ca,cf04d217-bfd6-4743-ae4b-bc98712959ca,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
...,...,...,...
5818,acdb8093-c93c-49d7-af05-f04cae009f99,acdb8093-c93c-49d7-af05-f04cae009f99,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
5819,e733c608-da84-49f1-a3ae-52a025b1cb3d,e733c608-da84-49f1-a3ae-52a025b1cb3d,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
5820,6d8cf85e-93bd-47ea-8a59-3e43fe4ef732,6d8cf85e-93bd-47ea-8a59-3e43fe4ef732,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
5821,e2d00db3-27b2-4996-89e2-5c1579af5d39,e2d00db3-27b2-4996-89e2-5c1579af5d39,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."
5822,db185596-c12d-41de-ab1d-0fb7ef877ff3,db185596-c12d-41de-ab1d-0fb7ef877ff3,"{'name [en_GB]': {'origin': 'PROVIDER', 'provi..."

We observe that `data_origin` column is nested.

In [9]:
# Flatten 'data_origin' column
data_origin_df = pd.json_normalize(df_meta['data_origin'])

# Add prefixes so we know where they came from
data_origin_df = data_origin_df.add_prefix('origin_')

# Drop original nested columns from df_meta
df_meta = df_meta.drop(columns=['data_origin'])

# Merge the flattened parts back
df_meta = pd.concat([df_meta, data_origin_df], axis=1)

In [10]:
df_meta

,mirakl_product_id,product_sku,origin_name [en_GB].origin,origin_name [en_GB].provider_code,origin_name [el_CY].origin,origin_name [el_CY].provider_code,origin_color.origin,origin_color.provider_code,origin_shortDescription [el_CY].origin,origin_shortDescription [el_CY].provider_code,...,origin_heelHeight.origin,origin_heelHeight.provider_code,origin_longDescription.origin,origin_longDescription.provider_code,origin_shortDescription.origin,origin_shortDescription.provider_code,origin_name.origin,origin_name.provider_code,origin_heelType.origin,origin_heelType.provider_code
0,d96975c5-0bea-41f6-a4a8-fdac53f374f3,d96975c5-0bea-41f6-a4a8-fdac53f374f3,PROVIDER,2077,PROVIDER,2077,PROVIDER,2077,PROVIDER,2077,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6f302b78-9a86-484e-894f-bb39220931a3,6f302b78-9a86-484e-894f-bb39220931a3,PROVIDER,2002,PROVIDER,2002,PROVIDER,2002,PROVIDER,2002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,70006973-aa9f-4176-9f38-0ba2c5a1b06f,70006973-aa9f-4176-9f38-0ba2c5a1b06f,PROVIDER,2167,PROVIDER,2167,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6b010b1d-7475-44dc-ad56-502769d2e742,6b010b1d-7475-44dc-ad56-502769d2e742,PROVIDER,2077,PROVIDER,2077,PROVIDER,2077,PROVIDER,2077,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,cf04d217-bfd6-4743-ae4b-bc98712959ca,cf04d217-bfd6-4743-ae4b-bc98712959ca,PROVIDER,3390,PROVIDER,3390,PROVIDER,3390,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5818,acdb8093-c93c-49d7-af05-f04cae009f99,acdb8093-c93c-49d7-af05-f04cae009f99,PROVIDER,2077,PROVIDER,2077,PROVIDER,2077,PROVIDER,2077,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5819,e733c608-da84-49f1-a3ae-52a025b1cb3d,e733c608-da84-49f1-a3ae-52a025b1cb3d,PROVIDER,3429,PROVIDER,3429,PROVIDER,3429,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5820,6d8cf85e-93bd-47ea-8a59-3e43fe4ef732,6d8cf85e-93bd-47ea-8a59-3e43fe4ef732,PROVIDER,2002,PROVIDER,2002,PROVIDER,2002,PROVIDER,2002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5821,e2d00db3-27b2-4996-89e2-5c1579af5d39,e2d00db3-27b2-4996-89e2-5c1579af5d39,PROVIDER,2077,PROVIDER,2077,PROVIDER,2077,PROVIDER,2077,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5822,db185596-c12d-41de-ab1d-0fb7ef877ff3,db185596-c12d-41de-ab1d-0fb7ef877ff3,PROVIDER,3429,PROVIDER,3429,PROVIDER,3429,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_sources

,provider_code,provider_sku,mirakl_product_id
0,2077,1071A091-101--EUM-18--WHITE / BLACK,d96975c5-0bea-41f6-a4a8-fdac53f374f3
1,2002,VN0A3MTJT2J1--417--BLACK,6f302b78-9a86-484e-894f-bb39220931a3
2,2167,IH6003-44.5,70006973-aa9f-4176-9f38-0ba2c5a1b06f
3,2077,CT2927-100--USAM-09--WHITE / BLACK / VOLT,6b010b1d-7475-44dc-ad56-502769d2e742
4,3390,468781-1870785842,cf04d217-bfd6-4743-ae4b-bc98712959ca
...,...,...,...
5818,2077,1636155--EUM-05--WHITE / SILVER / BLACK,acdb8093-c93c-49d7-af05-f04cae009f99
5819,3429,JI1349--1310--WHITE,e733c608-da84-49f1-a3ae-52a025b1cb3d
5820,2002,FLJELBLEA12WHBEI--401--WHITE,6d8cf85e-93bd-47ea-8a59-3e43fe4ef732
5821,2077,WS327-KA--EUM-04--CLOUD WHITE / BURGUNDY,e2d00db3-27b2-4996-89e2-5c1579af5d39
5822,3429,WS327-KA--EUM-05--CLOUD WHITE / BURGUNDY,db185596-c12d-41de-ab1d-0fb7ef877ff3

Our algorithms are **evaluated** on a manually labeled sample dataset. The labels correspond to variant groupings, which means that **only Task 2 can currently be evaluated**. However, Task 1 could be evaluated in a similar manner, provided we have a sample dataset labeled specifically for that task.

In [12]:
# Load the sample to evaluate the groups
sample_df = pd.read_csv("sample.csv")

Now that we have separate flattened dataframes we can investigate whether we have missing values and in which fields.

In [13]:
df_data.isna().sum()

EAN                                  0
size                                 0
brand                               11
color                               15
category                             0
returnable                           0
name [el_CY]                       608
name [en_GB]                         0
updateOnDelta                     5819
refinementColor                    733
variantGroupCode                     0
jiniusSkuMatchCode                   0
shortDescription [el_CY]          1336
shortDescription [en_GB]             0
mainImage.source                     0
mainImage.original_url               4
secondary_image_1.source           290
secondary_image_1.original_url     292
secondary_image_2.source           437
secondary_image_2.original_url     437
secondary_image_3.source           737
secondary_image_3.original_url     737
longDescription [en_GB]           5585
longDescription [el_CY]           5716
shoeType                          5681
shoeShape                         5822
fashionMaterial                   5808
shoeWidth                         5766
heelHeight                        5798
name                              5799
heelType                          5773
longDescription                   5799
shortDescription                  5799
dtype: int64

In [14]:
df_meta.isna().sum()

mirakl_product_id                                   0
product_sku                                         0
origin_name [en_GB].origin                          0
origin_name [en_GB].provider_code                 153
origin_name [el_CY].origin                        608
origin_name [el_CY].provider_code                 682
origin_color.origin                                15
origin_color.provider_code                        155
origin_shortDescription [el_CY].origin           1336
origin_shortDescription [el_CY].provider_code    1340
origin_secondary_image_2.origin                   437
origin_secondary_image_2.provider_code            446
origin_secondary_image_1.origin                   288
origin_secondary_image_1.provider_code            306
origin_shortDescription [en_GB].origin              0
origin_shortDescription [en_GB].provider_code      61
origin_secondary_image_3.origin                   737
origin_secondary_image_3.provider_code            741
origin_mainImage.origin                             0
origin_mainImage.provider_code                     16
origin_returnable.origin                            0
origin_size.origin                                  0
origin_size.provider_code                          11
origin_refinementColor.origin                     733
origin_category.origin                              0
origin_category.provider_code                     242
origin_updateOnDelta.origin                      1410
origin_brand.origin                                11
origin_brand.provider_code                        188
origin_returnable.provider_code                  1925
origin_longDescription [en_GB].origin            5585
origin_longDescription [en_GB].provider_code     5588
origin_refinementColor.provider_code             2549
origin_longDescription [el_CY].origin            5715
origin_longDescription [el_CY].provider_code     5719
origin_shoeType.origin                           5681
origin_shoeType.provider_code                    5681
origin_fashionMaterial.origin                    5804
origin_fashionMaterial.provider_code             5808
origin_shoeShape.origin                          5822
origin_shoeShape.provider_code                   5822
origin_shoeWidth.origin                          5766
origin_shoeWidth.provider_code                   5766
origin_heelHeight.origin                         5798
origin_heelHeight.provider_code                  5798
origin_longDescription.origin                    5799
origin_longDescription.provider_code             5799
origin_shortDescription.origin                   5799
origin_shortDescription.provider_code            5799
origin_name.origin                               5799
origin_name.provider_code                        5799
origin_heelType.origin                           5773
origin_heelType.provider_code                    5773
dtype: int64

In [15]:
df_sources.isna().sum()

provider_code        0
provider_sku         0
mirakl_product_id    0
dtype: int64

From the above we observe that some important fields (such as color, brand, descriptions) contain missing values.

In [16]:
# check the values of jiniusSkuMatchCode column
df_data["jiniusSkuMatchCode"].describe()

count     5823
unique       1
top         []
freq      5823
Name: jiniusSkuMatchCode, dtype: object

`jiniusSkuMatchCode` column is only has empty lists, although it appeared to have no missing values.

In [17]:
#check the number of records with empty EAN
df_data["EAN"].describe()

count     5823
unique     487
top         []
freq      5337
Name: EAN, dtype: object

In [18]:
df_data["EAN"].apply(lambda x: x == []).sum()

5337

From the 5823 observations, 5337 of them have empty EAN code and the remaining have a unique EAN code. So no products are grouped by the EAN code.

In [19]:
df_data['brand'].isna().sum()

11

In [20]:
df_data[df_data['brand'].isna()][['name [en_GB]','name', 'color', 'category', 'shortDescription', 'brand']]

     name [en_GB] name        color        category shortDescription brand
1075        C8979  NaN        Black  FaMeShSneakers              NaN   NaN
2258        C8979  NaN    All White  FaMeShSneakers              NaN   NaN
2559        C8979  NaN        Black  FaMeShSneakers              NaN   NaN
2941         C895  NaN        White  FaWoShSneakers              NaN   NaN
3856         C895  NaN        Black  FaWoShSneakers              NaN   NaN
4193         C667  NaN        White  FaWoShSneakers              NaN   NaN
4469         C872  NaN        White  FaWoShSneakers              NaN   NaN
4777        C8962  NaN        Black  FaWoShSneakers              NaN   NaN
5033         C667  NaN        White  FaWoShSneakers              NaN   NaN
5451         C666  NaN        White  FaWoShSneakers              NaN   NaN
5627         C872  NaN  Black White  FaWoShSneakers              NaN   NaN

In [21]:
df_data[df_data['brand'] == 'CALVIN KLEIN JEANS']

,EAN,size,brand,color,category,returnable,name [el_CY],name [en_GB],updateOnDelta,refinementColor,...,longDescription [el_CY],shoeType,shoeShape,fashionMaterial,shoeWidth,heelHeight,name,heelType,longDescription,shortDescription
148,[],45,CALVIN KLEIN JEANS,Black / White,FaMeShSneakers,true,Basket cupsole low leather sneakers,Basket cupsole low leather sneakers,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
335,[],45,CALVIN KLEIN JEANS,White,FaMeShSneakers,true,Retro tennis low laceup mtl,Retro tennis low laceup mtl,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,[],45,CALVIN KLEIN JEANS,White,FaMeShSneakers,true,Senakers,Senakers,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,[],42,CALVIN KLEIN JEANS,Black,FaMeShSneakers,true,Chunky cupsole authentic shoe,Chunky cupsole authentic shoe,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1204,[],43,CALVIN KLEIN JEANS,White,FaMeShSneakers,true,Chunky cupsole mono leather,Chunky cupsole mono leather,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1297,[],44,CALVIN KLEIN JEANS,Black,FaMeShSneakers,true,Retro tennis low laceup mtl,Retro tennis low laceup mtl,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992,[],41,CALVIN KLEIN JEANS,White,FaMeShSneakers,true,Claic cupsole iconic nylon shoe,Claic cupsole iconic nylon shoe,NaN,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3580,[],40,CALVIN KLEIN JEANS,Black,FaWoShSneakers,true,Chunky cupsole laceup leather shoe,Chunky cupsole laceup leather shoe,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5088,[],40,CALVIN KLEIN JEANS,White,FaWoShSneakers,true,Retro tennis su-mesh wn,Retro tennis su-mesh wn,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df_data[df_data['brand'] == 'CALVIN KLEIN']

,EAN,size,brand,color,category,returnable,name [el_CY],name [en_GB],updateOnDelta,refinementColor,...,longDescription [el_CY],shoeType,shoeShape,fashionMaterial,shoeWidth,heelHeight,name,heelType,longDescription,shortDescription
4411,[5299901986314],36,CALVIN KLEIN,White,FaWoShSneakers,true,Eva runner low lace shoes,Eva runner low lace shoes,None,white,...,NaN,0090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The outputs above reveal inconsistencies in brand naming (e.g., *LIU JO SHOES* vs *LIU JO*). To ensure consistency, we apply a brand name mapping that standardizes all variations.

In [23]:
df_data['brand'].unique()

array(['ASICS', 'VANS', 'ADIDAS', 'NIKE', 'PUMA', 'CONVERSE',
       'ADIDAS ORIGINALS', 'UNDER ARMOUR', 'SAUCONY', 'REEBOK', 'JORDAN',
       'DIESEL', 'CHAMPION', 'NEW BALANCE', 'FRED PERRY', 'SKECHERS',
       'ON RUNNING', 'EA7', 'JOMA', 'CARRERA', "LEVI'S", 'VEJA',
       'PEPE SHOES', 'TALBOT SHOES', 'U.S. POLO ASSN.',
       'PEPE JEANS LONDON', 'TOMMY HILFIGER', 'CALVIN KLEIN JEANS', 'DC',
       'STEFAN', 'ANTONY MORATO', 'TOMMY JEANS', 'KAPPA', 'LYLE & SCOTT',
       'HACKETT', 'KARL KANI', 'SERGIO TACCHINI', 'TAMARIS', 'REVERSE',
       'BAZAAR CHARM', 'MORK EXCLUSIVE', 'LACOSTE', 'SOUTHPORT',
       'SALOMON', 'GAUDI', 'JACK & JONES', 'FUNKY BUDDHA', 'HUGO BOSS',
       'FENOMILANO', 'FILA', 'RHAPSODY', 'BOSTON SPORT CLUB', 'MIMSOGA',
       'SUN68', 'LIU JO SHOES', 'LOTTO', 'PLATO', 'MIZUNO', 'ADMIRAL',
       'BROOKS', 'SIKSILK', 'NICO', 'ICE PLAY', 'BHPC', 'GUESS DENIM',
       'PARIS', 'NO NAME ATHENS', 'GUESS', 'ATLANTA', nan,
       'BE YOU, U.S. POLO ASSN', 'THE NORTH FACE', 'EMPORIO ARMANI',
       'PLEIN SPORT', 'LA MARTINA', 'COLUMBIA', 'GAP', 'REEF', 'TOMS',
       'STARTER', 'NEW YORK POLO CLUB', 'BIG STAR', 'MAKRIS', 'ICEBERG',
       'S/B', 'LE COQ SPORTIF', 'SUPERDRY', 'PERIPATI', 'CLARKS',
       'TATA ITALIA', 'GAS', 'ELLESSE', 'KANGAROOS', 'ACUPUNCTURE',
       'HOKA', 'LIU JO', 'MINDY SHOES', 'VIA MARTE', 'GIVANA',
       'RAFAELA BELGINI', 'BELLAMICA', 'PUNTO', 'BUFFALO', 'DKNY',
       'ENVIE', 'ROCCOBAROCCO', 'UGG', 'VIZZANO', 'JUICY COUTURE',
       'BENETTON', 'TRUSSARDI', 'IOANNOU SHOES', 'ASH', 'ROXY',
       'NATURAL WORLD SHOES', 'LAPIERCE', 'MARQUIIZ', 'KAPRIS', 'PINKO',
       'CALVIN KLEIN', 'SWEET SHOES', 'D.FRANKLIN', 'PICCADILLY',
       'DIAMANTIQUE', 'CRASH', 'LUMBERJACK', 'SANTE', 'IDEAL',
       'MY LADIDA BOUTIQUE'], dtype=object)

In [24]:
brand_mapping = {
    'ADIDAS ORIGINALS': 'ADIDAS',
    'CALVIN KLEIN JEANS': 'CALVIN KLEIN',
    'LIU JO SHOES': 'LIU JO',
    'GUESS DENIM': 'GUESS',
    'TOMMY JEANS': 'TOMMY HILFIGER',
    'PEPE JEANS LONDON': 'PEPE JEANS',
    'BE YOU, U.S. POLO ASSN': 'U.S. POLO ASSN.',
    'BHPC': 'BEVERLY HILLS POLO CLUB',
    'EA7': 'EMPORIO ARMANI',
    'NO NAME ATHENS': 'NO NAME'
}

In [25]:
df_data_copy = df_data.copy()

df_data_copy['brand_label'] = df_data_copy['brand'].replace(brand_mapping)

In [26]:
df_data['brand'].nunique()

128

In [27]:
df_data_copy['brand'].nunique()

128

In [28]:
df_data_copy['brand_label'].nunique()

121

In [29]:
df_data_copy[df_data_copy['brand_label'] == 'ADIDAS']['name [en_GB]'].unique()

array(['Adidas response', 'Adidas gazelle shoes', 'Swift run 22',
       'Adistar 2 men', 'Midcity mid',
       "Adidas men's supernova stride shoes", 'Duramo speed men',
       'Adidas gazelle indoor', 'Gazelle shoes', 'Cloudfoam go lounge',
       'Midcity low', 'Strutter', 'Response runner unisex',
       'Response super mens', 'Adidas grand court base 2.0',
       'Stan smith vegan', 'Forest grove sneakers', 'Znsored hi mens',
       'Fukasa run', 'Cloudfoam comfy', 'Urban court',
       'Adidas alphaboost v1', 'Alphabounce + c', 'Samba classic',
       'Copa mundial', 'Ozelle', 'Adistar 3', 'X_plrphase',
       'Ultimashow 2.0',
       'Adidas questar             greone/cblack/grethr', 'Advantage 2.0',
       'Adidas copa pure.3 tf', 'Grand court 2.0', 'Samba og',
       'Adidas handball spezial', 'Handball spezial', 'Runfalcon 3.0',
       'Runfalcon 5', 'Adidas men duramo sl', 'Copa pure.1 firm ground',
       "Adidas men's duramo speed shoes", 'Park st',
       'Adidas men runfalcon 3.0 (hp7544)', 'Adidas campus 00s',
       'Supernova 2 men', 'Ubounce dna', 'Questar 3 mens', 'Adizero sl',
       'Duramo protect mens',
       'Adidas bounce legends      carbon/goldmt/cblack', 'X9000l4 u',
       'Kaptir 3.0', 'Sl 72 rs', 'Duramo sl', 'Galaxy 7 men',
       'X_plr pulse', 'Adidas men courtblock', 'Advantage base',
       'Duramo sl men', 'Crazyfast.4 fxg',
       'Adidas pureboost 22        ftwwht/ftwwht/crywht',
       'Adidas sl 72 rs', 'Adidas men breaknet 2.0 shoes (id7110)',
       '4dfwd 2 mens', 'Adidas x_plrphase          cblack/cblack/ftwwht',
       'Osade', 'Galaxy 6 men', 'Duramo sl2', 'Courtblock',
       'Adidas response super 3.0  cblack/cblack/ftwwht',
       'Adidas coreracer           tecind/legink/cblack', 'Nmd_v3',
       '4dfwd 4 men', 'Alphaboost v1 mens', 'Gazelle', 'Alphaboost v1',
       'Ozmillen', 'Adidas fluidflow 2.0', 'Adidas galaxy 6 m',
       '4dfwd 3 men', 'Kantana', 'Vl court 3.0',
       'Adidas men advantage 2.0',
       'Runfalcon 2.0       cblack/cblack/gresix', 'Ownthegame 3.0',
       '4dfwd 2 men', 'Adidas ozweego', 'Pureboost 22',
       'Adidas men advantage base  (gw2063)', 'Adidas web boost',
       'Adidas questar             cblack/carbon/gresix',
       'Adidas gazelle', 'Questar 3 men', 'Gamecourt 2 men',
       "Adidas men's alphaboost v2 shoes", 'Adidas racer tr21',
       'Galaxy 7', 'Questar mens', 'Swift run 23', 'Supernova men',
       'Adi2000', 'Forum low cl', 'Adidas men duramo sl2 mens',
       'Adidas response cl', 'Court team bounce volley',
       'Adidas men duramo sl (ie7261)', 'Ownthegame 2.0', 'Racer tr23',
       'Adidas stan smith', 'Lite racer 2.0',
       "Adidas men's barreda decode shoes", 'Adidas galaxy 7', 'Response',
       'Ultrabounce wide', 'Adidas runfalcon 3.0',
       'Adidas stan smith mens shoes', 'Neo mens racer tr21',
       'Adidas men valentino courtblock', 'Crazyfast.4 tf',
       'Adidas men duramo sl  (id9849)',
       'Adidas forum 84 hi         cgreen/cwhite/bogold', 'Fx3631',
       'Adidas response cl         crywht/wonwhi/crywht',
       'Adidas adi2000',
       'Adidas nmd_v3              ftwwht/ftwwht/gretwo', 'Campus 00s',
       'X crazyfast elite f', 'Adidas men vs pace 2.0',
       'Adidas men galaxy 7', 'Duramo 10', 'Campus oos',
       'Adidas men courtblock shoes (if6504)',
       'Adidas men duramo sl shoes (ie7968)', 'Supernova stride mens',
       'Ultimashow          cblack/cblack/ftwwht', 'Ultrabounce',
       'Run 60s', 'N-5923', 'Ozweego             ftwwht/ftwwht/cblack',
       'Adidas questar             cblack/ftwwht/gretwo', 'Breaknet 2.0',
       'Campus 00', 'Adidas x9000l4 m', 'Duramo mens',
       'Adidas vs pace 2.0', 'Adistar 3 men', 'X crazyfast elite l',
       'Adidas runfalcon 2.0       ftwwht/cblack/vivred',
       "Adidas men's vl court 3.0 shoes", 'Adidas nmd v3',
       'Adidas duramo 10           cblack/cblack/cblack', 'Adidas  nmd',
       'Galaxy 6 mens', 'Gazelle messi', "Adidas men's lightblaze shoes",
       'Adidas men duramo sl shoes (ie7967)', 'Response super men',
       'Adidas galaxy 6 m          dkblue/grespa/aurbla',
       'Switch fwd 2 mens',
       'Adidas retropy e5          cblack/cblack/gresix',
       'Adidas gazelle bold womens shoes', 'Crazychaos 2000',
       'Adidas retropy e5          olistr/ftwwht/shaoli', 'Avryn',
       'Switch fwd mens', 'Adidas galaxy 6', 'Adidas ownthegame 2.0',
       'Adi2000 ftwwht/cblack/cwhite', 'Adidas advantage',
       'Alphabounce +', 'Court 24', 'Adifom climacool', 'Oztral',
       'Courtbeat', 'Stan smith', 'Equipment support', 'Adidas duramo',
       'Adidas ozmillen', 'Zx 22 boost', 'Adizero sl2 mens',
       'Adidas runfalcon 3.0 tr', 'Fluidflow 2.0', 'Ultrarun 5',
       'Flowboost', 'Crazyfast club tf', 'X_plrboost', 'Showtheway 2.0',
       'Hoops 3.0 summer', 'Eq21 run', 'Superstar',
       'Adidas avryn               cgreen/gretwo/cwhite',
       'Adidas ownthegame 2.0      grefiv/magold/cblack', 'Pureboost 5',
       "Adidas men's advantage base 2.0 shoes", 'Neo mens hoops high',
       'Ultimashow', 'Adidas eq21 run', 'Questar 2 men',
       'Adidas men copa pure 2 club firm ground',
       'Adidas ownthegame 2.0      cblack/grefiv/ftwwht',
       'Adidas duramo sl m         cblack/ftwwht/carbon',
       'Adidas men grand court 2.0', 'Solar control men', 'Hoops 3.0 mid',
       'Response cl', 'Adidas men ultrarun 5', 'Supernova 3 gtx',
       'Adidas duramo 10           legink/vivred/ftwwht',
       'Adidas men courtjam control 3',
       'X9000l3 m c.rdy     gretwo/ftwwht/aciyel',
       'Response super 3.0 mens', 'X speedportal.1 sg', 'Galaxy 7 mens',
       'Gazelle indoor', 'Switch fwd 2', 'Superstar vegan',
       'Switch run men', 'Pureboost 23', 'Duramo sl2 men',
       'Adidas runfalcon 3.0       cblack/ftwwht/cblack',
       'Adidas rivalry low', 'Adidas men duramo speed (ie7268)',
       'Grandcourt alpha 00s', 'Adidas men alphaedge',
       'X crazyfast.3 techfit',
       'Adidas runfalcon 3.0       gresix/cblack/carbon',
       "Adidas men's response shoes", 'Grand court base 2.',
       'Duramo 10 mens', 'I-5923', 'Barreda decode',
       'Adidas campus 00s beta', 'Adidas crazy chaos 2000 shoes',
       'Adidas men solarcontrol 2 (hp9648)', 'Runfalcon 3.0 training',
       'Duramo speed mens', 'Adidas men alphaboost v1 shoes (ig3640)',
       'Copa pure 2 league', 'Campus 00s beta', 'Runfalcon 2.0',
       "Adidas men's trae unlimited shoes", 'Adidas men questar 3',
       'Adidas lite racer 3.0      ftwwht/royblu/ftwwht',
       'Adidas swift run 22        cblack/cblack/grefiv',
       "Adidas men's response super shoes", 'Adidas adifom climacool',
       'Ozweego', "Adidas men's grand court alpha shoes",
       'Adidas strutter            ftwwht/dkblue/msilve', 'Questar 3',
       'Ozelia', 'Adidas ozelia', 'Court magnetic', 'Hoops 3.0',
       'Adidas pureboost 22        cblack/cblack/carbon',
       'Response super 3.0', 'Breaknet',
       'Adidas runfalcon 3.0       betsca/ftwwht/cblack',
       'Adidas forum 84 low        clowhi/orbgry/owhite', 'Pureboost jet',
       'Stan smith mens shoes', 'X speedflow.3 indoor shoes',
       'Crazyfast elite 2g/3g ag', 'Adidas grand court alpha',
       'Samba super', 'Vs pace 2.0', "Adidas men's court shoes",
       'Questar', 'Duramo protect', 'Run 70s 2.0', 'Pro n3xt 2021',
       'X_plrpath',
       'Adidas men grand court td lifestyle court casual shoes (id30',
       'Samba', 'Duramo speed 2', 'Adidas duramo 10', 'Duramo sl mens',
       'Copa pure 2 club techfit',
       'Adidas stan smith          cwhite/owhite/panton',
       'Adidas eq21 run            ftwwht/cblack/gretwo',
       'Pureboost 22 h.rdy mens', 'Ozelle mens', 'Barreda decode v2',
       'Adidas men ultimashow  (fx3624)', 'Adidas trainer v',
       'Adidas men galaxy 6', 'Nova run shoes', 'Tracefinder',
       'Ultrabounce c', 'Adidas x_plrphase          dshgry/silvmt/luclem',
       'Superstar           ftwwht/cblack/ftwwht', 'Ozweego training',
       'Adidas x crazyfast.4 tf    ftwwht/cblack/luclem', 'Alphaedge +',
       'Ultrarun 5 training', 'Adidas forum low',
       'Adidas runfalcon 2.0       halsil/turbo/cblack', 'Switch fwd men',
       'Supernova 2 x parley', "Adidas men's advantage 2.0 shoes",
       'Adidas men court revival shoes (hp2604)',
       'Adidas men adistar cs 2.0 shoes (id0367)', 'Galaxy 5',
       'Adidas advantage base', 'Crazyfast messi.4 fxg', 'Gy6348',
       'Adidas stan smith          cwhite/owhite/prered',
       'Adidas x_plrboost          cwhite/cblack/owhite',
       'Ultrabounce trail',
       'Adidas stan smith          ftwwht/shanav/maggre',
       "Adidas men's mullaly low shoes", 'Solarcontrol 2 men',
       'Adidas men x_plrphase  (ig4777)',
       "Adidas men's ultimashow 2.0 shoes", 'X ghosted.3 in',
       'Adidas x_plrboost          cblack/ftwwht/pullim',
       'Speedportal.4 fxg mens',
       'Eq21 run            cblack/cblack/cblack',
       'Adidas men adistar 2.0 shoes (gw1961)',
       'Adidas galaxy 5            ftwwht/gretwo/gresix',
       'Copa sense.1 sg', 'Front court',
       'Adidas runfalcon 3.0       cblack/cblack/carbon',
       'Showtheway 2.0 unisex',
       'Adidas retropy e5          cblack/ftwwht/gumm2',
       'Adidas duramo sl m         legink/ftwwht/cblack',
       'Adidas samba og', 'Adidas men runfalcon 3 shoes (hp7546)',
       'Racer TR23', 'Multix', "Adidas men's a.e. 1 low trainers",
       'Adidas men x crazyfast club flexible ground boots (ig0618)',
       'Adidas forum  low chsogr/cwhite/gum3', 'Grand court mens',
       'Adidas men advantage base 2.0', 'Rivalry low',
       'Adidas men ultrabounce', 'Adidas men advandage base',
       'Adidas men x_plr path shoes (id0465)', 'Cloudfoam move',
       'Adidas zx 2k 4d', 'Adidas men ultrabounce shoes (hp5778)',
       'Copa pure III leagu', 'Pureboost 22 mens',
       'Adidas x_plrboost          gretwo/cgreen/silvmt',
       'Ultradream dna', 'Supernova stride 2', 'Runfalcon 2.0 mens',
       'Adidas run 70s',
       'Adidas unisex climacool ventania shoes (fz1744)',
       'Adidas men x9000l2 shoes (s23651)', 'Switch run mens',
       'Speedportal.3 fg', 'Adidas questar',
       'Adidas duramo 10           grefou/ironmt/flaora', 'Niteball',
       'Copa pure 2 club fx', 'Adidas niteball',
       "Adidas men's lightshift shoes", 'Adidas men questar 2',
       'Questar 2 mens', 'Grand court', 'Adidas women grand court',
       'Gazelle bold women', 'Adidas ozelia w', 'Adidas sl 72 og w',
       'Samba og women', 'Sl 72 og women', 'Advantage', 'Lightblaze',
       'Adidas gazelle bold w', 'Adidas ozgaia w',
       'Adidas x_plrboost          grefiv/cblack/clpink',
       'Ozmillen women', 'Campus 00s women',
       "Adidas women's grand court td lifestyle court casual shoes",
       'Adidas women zx 1k boost 2.0 shoes (gw6869)',
       "Adidas women's vl court 3.0 shoes", 'Ozgaia women',
       'Adidas women breaknet 2.0 shoes (id0471)',
       'Adidas women racer tr23 shoes (id7884)',
       'Adidas gazelle indoor w', 'Hp8962', 'Gazelle j',
       "Adidas women's grand court alpha shoes",
       'Adidas women grazychaos 2000', 'Grand court womens',
       'Adidas campus 00s w', 'Puremotion se', 'Puremotion 2.0',
       'Grand court platform', 'Superstar bonega women',
       'Adidas adidas taekwondo la', 'Handball spezial women',
       'Vl court bold', 'Superstar women', 'Ultrabounce women',
       'Gazelle indoor women', 'Nite jogger',
       'Nite jogger w       trupnk/silvmt/cpurpl', 'Qt racer sport',
       'Stan smith bonega women', 'Id2272', 'Adidas taekwondo la',
       'Ozelia junior', 'Adidas hyperturf w         wonqua/wonwhi/owhite',
       'Avryn_x', 'Grand court alpha 0',
       'Adidas women multix shoes (fz3455)', 'Neo coneo qt women shoes',
       'Adidas temper run 2 w', 'Roguera', 'Adidas stan smith w',
       'Stan smith women', 'Stan smith j', 'Postmove se', 'Sl 72 og',
       'Adidas women grand court base 2', 'Adidas gazelle w', 'Nmd_w1',
       'Adidas stan smith w        white', 'Nmd_r1 women',
       'Ultrabounce womens', 'Adidas qt racer 3.0', 'Kaptir flow',
       'Neo run 70s womens shoes', 'Court platform', 'Forum bold stripes',
       'Nizza platform mid womens', 'Stan smith millencon women',
       'Gazelle bold womens shoes',
       'Adidas women grand court td lifestyle court casual shoes (gw',
       'Superstar xlg women', 'Grand court alpha 00s', 'Swift run',
       'Adidas crazychaos 2000', 'Web boost women', 'Sambae women',
       'Temper run 2 women', 'Znchill', 'Adidas handball spezial w',
       'Qt racer 2.0', 'Neo cf advantage women shoes',
       'Adidas women court funk shoes (hp9458)',
       'Neo advantage leather women shoes', 'Women sneakers Ie8149',
       'Zx flux womens', 'Court platform cln', 'Campus 00s beta women',
       'Adidas adidas astir w', 'Multix junior', 'Special 21',
       'Adidas ultrabounce w', 'Adidas samba messi',
       "Adidas women's urban court shoes", 'Adidas sl 72 og',
       'Adidas samba lt w', 'Court flight',
       'Adidas lite racer 3.0      ftwwht/mapume/ftwwht',
       "Adidas originals women's samba", 'Adidas samba og w',
       'Samba lt women', 'Womens postmove se', 'Crazychaos',
       "Adidas women's cloudfoam go sock shoes", 'Eclyptix 2000',
       'Adidas nmd_r1 w', 'Adidas samba xlg', 'Adidas forum xlg w',
       'Gazelle bold shoes', 'Adidas superstar w',
       'Adidas superstar w         ftwwht/orange/royblu', 'Ozweego women',
       'Adidas court', 'Court funk', 'Adidas superstar xlg w',
       'Adizero aruku women', "Adidas women's vl court bold shoes",
       'Adidas equipment csg 91 w  ftwwht/prered/grethr', 'Zx 1k boost',
       'Adidas women grazychaos', 'Rivalry low womens', 'Mavia x',
       'Retropy f2', 'Adidas women lite racer 3.0',
       "Adidas women's court platform shoes", 'Samba xlg',
       'Adidas superstar w         ftwwht/halblu/acired',
       'Adidas ozmillen w', "Adidas women's courtblock shoes", 'Arkyn',
       'Adidas women strutter', 'Adidas forum bold w',
       'Handball spezial w', 'Tokyo women', 'Team court womens',
       'Adidas adifom stan slide w', 'Adidas grand court 2.0', 'Retroset',
       'Adidas forum bonega w', 'Court silk',
       'Adidas court platform shoes', 'Adidas nmd_w1',
       'Puremotion 2.0 womens', 'Adidas women alpha bounce',
       'Adidas forum bold w        ftwwht/cblack/ftwwht', 'Sleek',
       'Adidas Ultrabounce', 'Adidas nmd_r1 w strap', 'Adidas falcon w',
       'Adidas women postmove se  (ig7903)', 'Gamecourt 2 womens',
       "Adidas women's cloudfoam go lounger shoes",
       'Adidas women gamecourt 2', 'Nizza platform mid women',
       'Adidas response cl w', 'X_plrboost puffer', 'Falcon rx w',
       'Adidas astir women',
       'Adidas x9000l4 h.rdy w     ftwwht/ftwwht/magmau',
       'Adidas vl court bold j', 'Adidas vl court', 'Forum bonega women',
       "Adidas women's grand court base 2.0 shoes", 'Court funk womens',
       'Stan smith junior', 'Court platform womens',
       'Adidas women postmove se (gy6683)', 'Forum low women',
       'Continental 80 stripes',
       'Adidas women vl court 3.0 low skateboarding shoes (id8797)',
       'Adidas women lite racer 4.0', 'Response cl women',
       'Nizza hi xy22', 'Adidas women osade  (ig7330)',
       'Forum bold women', 'Startyourrun womens', 'Adidas women ozelle',
       'Adidas tokyo w', 'Adidas women court platform shoes (gv9000)',
       'Adidas women znchill lightmotion+ lifestyle adult shoe (hp60',
       'Gazelle leather', 'Adidas zx wavian w', 'Forum bold womens',
       'Adifom q', 'Explorer women shoes',
       'Adidas women speedmotion shoes (hp5693)', 'Adidas ozweego w',
       'Adifom sltn women', 'Neo womens ozelle', 'Speedmotion',
       'Adidas superstar bonega w', 'X_plr', 'Adidas sambae w'],
      dtype=object)

## Task 1: Match identical products

#### **Approach 1:** Group products using existing fields

In this approach, we assume that products with identical `brand`, `color`, `category`, `'name` and `description` are identical products, so we perform a grouping based on these attributes.

In [30]:
# inspect features
print(df_data.columns)

Index(['EAN', 'size', 'brand', 'color', 'category', 'returnable',
       'name [el_CY]', 'name [en_GB]', 'updateOnDelta', 'refinementColor',
       'variantGroupCode', 'jiniusSkuMatchCode', 'shortDescription [el_CY]',
       'shortDescription [en_GB]', 'mainImage.source',
       'mainImage.original_url', 'secondary_image_1.source',
       'secondary_image_1.original_url', 'secondary_image_2.source',
       'secondary_image_2.original_url', 'secondary_image_3.source',
       'secondary_image_3.original_url', 'longDescription [en_GB]',
       'longDescription [el_CY]', 'shoeType', 'shoeShape', 'fashionMaterial',
       'shoeWidth', 'heelHeight', 'name', 'heelType', 'longDescription',
       'shortDescription'],
      dtype='object')

In [31]:
#column "name" is empty in almost all rows
df_data["name"].isna().sum()/df_data.shape[0]

0.9958784131890778

In [32]:
#find the only products with non-empty "name" column
df_data[df_data["name"].notna()]

,EAN,size,brand,color,category,returnable,name [el_CY],name [en_GB],updateOnDelta,refinementColor,...,longDescription [el_CY],shoeType,shoeShape,fashionMaterial,shoeWidth,heelHeight,name,heelType,longDescription,shortDescription
1340,[198376576226],43,SKECHERS,Black,FaMeShSneakers,true,Skechers 118317 men shoes,Skechers 118317 men shoes,NaN,black,...,SKECHERS 118317 MEN SHOES / GLIDE STEP,0030,NaN,NaN,medium,NaN,SKECHERS 118317 MEN SHOES / GLIDE STEP,other,SKECHERS 118317 MEN SHOES / GLIDE STEP,SKECHERS 118317 MEN SHOES
1458,[198376147365],41,SKECHERS,Black,FaMeShSneakers,true,210890 bbk skechers men shoes,210890 bbk skechers men shoes,NaN,black,...,210890 BBK SKECHERS MEN SHOES/ SLIP IN,0030,NaN,NaN,medium,NaN,210890 BBK SKECHERS MEN SHOES,other,210890 BBK SKECHERS MEN SHOES/ SLIP IN,210890 BBK SKECHERS MEN SHOES
1805,[196989378503],42,SKECHERS,Grey,FaMeShSneakers,true,Skechers 232700 gry men shoes,Skechers 232700 grymen shoes,NaN,grey,...,SKECHERS 232700 GRY MEN SHOES / ARCH FIT,0020,NaN,NaN,medium,NaN,SKECHERS 232700 GRY MEN SHOES / ARCH FIT,other,SKECHERS 232700 GRY MEN SHOES / ARCH FIT,SKECHERS 232700 GRY MEN SHOES
1853,[196989378527],43,SKECHERS,Grey,FaMeShSneakers,true,Skechers 232700 gry men shoes,Skechers 232700 grymen shoes,NaN,grey,...,SKECHERS 232700 GRY MEN SHOES / ARCH FIT,0020,NaN,NaN,medium,NaN,SKECHERS 232700 GRY MEN SHOES / ARCH FIT,other,SKECHERS 232700 GRY MEN SHOES / ARCH FIT,SKECHERS 232700 GRY MEN SHOES
2443,[198376147419],43,SKECHERS,Black,FaMeShSneakers,true,210890 bbk skechers men shoes,210890 bbk skechers men shoes,NaN,black,...,210890 BBK SKECHERS MEN SHOES/ SLIP IN,0030,NaN,NaN,medium,NaN,210890 BBK SKECHERS MEN SHOES,other,210890 BBK SKECHERS MEN SHOES/ SLIP IN,210890 BBK SKECHERS MEN SHOES
3112,[197976864054],41,SKECHERS,Black,FaWoShSneakers,true,Skechers 150370 bbk women shoes,Skechers 150370 bbk women shoes,None,black,...,SKECHERS 150370 BBK WOMEN SHOES / AIR SOLE,0020,NaN,NaN,medium,NaN,SKECHERS 150370 BBK WOMEN SHOES,other,SKECHERS 150370 BBK WOMEN SHOES / AIR SOLE,SKECHERS 150370 BBK WOMEN SHOES
3455,[196989863429],38,SKECHERS,Black/gold,FaWoShSneakers,true,Skechers 117513 women shoes,Skechers 117513 women shoes,None,black,...,SKECHERS 117513 WOMEN SHOES / MEMORY FOAM,0020,NaN,NaN,medium,NaN,SKECHERS 117513 WOMEN SHOES / BOBS SPORT,other,SKECHERS 117513 WOMEN SHOES / MEMORY FOAM,SKECHERS 117513 WOMEN SHOES
3457,[196989863405],37,SKECHERS,Black/gold,FaWoShSneakers,true,Skechers 117513 women shoes,Skechers 117513 women shoes,None,black,...,SKECHERS 117513 WOMEN SHOES / MEMORY FOAM,0020,NaN,NaN,medium,NaN,SKECHERS 117513 WOMEN SHOES / BOBS SPORT,other,SKECHERS 117513 WOMEN SHOES / MEMORY FOAM,SKECHERS 117513 WOMEN SHOES
3498,[198376755850],39,SKECHERS,Beige/silver,FaWoShSneakers,true,Skechers 150246 ntsl women shoes,Skechers 150246 ntsl women shoes,NaN,beige,...,SKECHERS 150246 NTSL WOMEN SHOES / MEMORY FOAM,0020,NaN,NaN,medium,NaN,SKECHERS 150246 NTSL WOMEN SHOES,other,SKECHERS 150246 NTSL WOMEN SHOES / MEMORY FOAM,SKECHERS 150246 NTSL WOMEN SHOES
3550,[198739014495],41,SKECHERS,Black,FaWoShSneakers,true,Skechers 150562 bklv women shoes,Skechers 150562 bklv women shoes,NaN,black,...,SKECHERS 150562 BKLV WOMEN SHOES / MEMORY FOAM,0020,NaN,NaN,medium,NaN,SKECHERS 150562 BKLV WOMEN SHOES,other,SKECHERS 150562 BKLV WOMEN SHOES / MEMORY FOAM,SKECHERS 150562 BKLV WOMEN SHOES
3722,[197976371736],37,SKECHERS,Rasberry,FaWoShSneakers,true,129000 skechers women shoes,129000 skechers women shoes,None,grey,...,129000 SKECHERS WOMEN SHOES / GO RUN,0020,NaN,NaN,medium,NaN,SKECHERS GO RUN ELEVATE 2.0,other,129000 SKECHERS WOMEN SHOES / GO RUN ELEVATE...,129000 SKECHERS WOMEN SHOES / GO RUN
4061,[198376766467],37,SKECHERS,Black,FaWoShSneakers,true,Skechers 150215 women shoes,Skechers 150215 women shoes,NaN,black,...,SKECHERS 150215 WOMEN SHOES / AIR COOLED / MEM...,0020,NaN,NaN,medium,NaN,SKECHERS 150215 WOMEN SHOES,other,SKECHERS 150215 WOMEN SHOES / AIR COOLED / MEM...,SKECHERS 150215 WOMEN SHOES
4090,[197976500211],40,SKECHERS,Beige,FaWoShSneakers,true,117550/tpe skechers women shoes,117550/tpe skechers women shoes,None,beige,...,117550/TPE SKECHERS WOMEN SHOES/MEMORY FOAM,0020,NaN,NaN,medium,NaN,BOBS INFINITY SKECHERS WOMEN SHOES,other,BOBS INFINITY SKECHERS WOMEN SHOES,117550/TPE SKECHERS WOMEN SHOES
4302,[196989863566],39,SKECHERS,Beige/gold,FaWoShSneakers,true,Skechers 117513 women shoes,Skechers 117513 women shoes,None,beige,...,SKECHERS 117513 WOMEN SHOES / MEMORY FOAM,0020,NaN,NaN,medium,NaN,SKECHERS 117513 WOMEN SHOES / BOBS SPORT,other,SKECHERS 117513 WOMEN SHOES / MEMORY FOAM,SKECHERS 117513 WOMEN SHOES
4599,[197976169685],41,SKECHERS,White,FaWoShSneakers,true,Skechers 117497 ofwh women shoes,Skechers 117497 ofwh women shoes,None,white,...,SKECHERS 117497 OFWH WOMEN SHOES / SLIP INS,0030,NaN,NaN,medium,NaN,SKECHERS 117497 OFWH WOMEN SHOES,other,SKECHERS 117497 OFWH WOMEN SHOES / SLIP INS,SKECHERS 117497 OFWH WOMEN SHOES
4793,[195204965276],38,SKECHERS,Mauve,FaWoShSneakers,true,Skechers 128326 mve women shoes,Skechers 128326 mve women shoes,None,pink,...,SKECHERS 128326 MVE WOMEN SHOES / GO RUN,0020,NaN,NaN,medium,NaN,SKECHERS 128326 MVE WOMEN SHOES / GO RUN,other,SKECHERS 128326 MVE WOMEN SHOES / GO RUN,SKECHERS 128326 MVE WOMEN SHOES
5003,[196989863528],37,SKECHERS,Beige/gold,FaWoShSneakers,true,Skechers 117513 women shoes,Skechers 117513 women shoes,None,beige,...,SKECHERS 117513 WOMEN SHOES / MEMORY FOAM,0020,NaN,NaN,medium,NaN,SKECHERS 117513 WOMEN SHOES / BOBS SPORT,other,SKECHERS 117513 WOMEN SHOES / MEMORY FOAM,SKECHERS 117513 WOMEN SHOES
5349,[4099758560467],41,KANGAROOS,Black,FaWoShSneakers,true,Kangaroos 30195 k rf bethy,Kangaroos 30195 k rf bethy,None,black,...,KangaROOS 30195 K RF BETHY/ WOMEN SHOES,0020,NaN,NaN,medium,NaN,KangaROOS 30195 K RF BETHY,other,KangaROOS 30195 K RF BETHY/ WOMEN SHOES,KangaROOS 30195 K RF BETHY
5395,[198376826420],37,SKECHERS,Nature / Pink,FaWoShSneakers,true,Skechers 129008 ntpk women shoes,Skechers 129008 ntpk women shoes,None,beige,...,SKECHERS 129008 NTPK WOMEN SHOES / GO RUN,0020,NaN,NaN,medium,NaN,SKECHERS 129008 NTPK WOMEN SHOES,other,SKECHERS 129008 NTPK WOMEN SHOES / GO RUN / GO...,SKECHERS 129008 NTPK WOMEN SHOES
5404,[196311867835],37,SKECHERS,Grey,FaWoShSneakers,true,Skechers 149713 gytq women shoes,Skechers 149713 gytq women shoes,None,grey,...,SKECHERS 149713 GYTQ WOMEN SHOES / ARCH FIT,0020,NaN,NaN,medium,NaN,SKECHERS 149713 GYTQ WOMEN SHOES,other,SKECHERS 149713 GYTQ WOMEN SHOES / ARCH FIT,SKECHERS 149713 GYTQ WOMEN SHOES
5417,[197976363144],38,SKECHERS,Grey/lime,FaWoShSneakers,true,129000 skechers women shoes,129000 skechers women shoes,None,grey,...,129000 SKECHERS WOMEN SHOES / GO RUN,0020,NaN,NaN,medium,NaN,SKECHERS GO RUN ELEVATE 2.0,other,129000 SKECHERS WOMEN SHOES / GO RUN ELEVATE...,129000 SKECHERS WOMEN SHOES / GO RUN
5454,[4099758556835],38,KANGAROOS,White,FaWoShSneakers,true,Kangaroos 30178 0001 k nj crush,Kangaroos 30178 0001 k nj crush,None,white,...,KangaROOS 30178 0001 K NJ CRUSH / SNEAKER,0030,NaN,NaN,medium,NaN,KangaROOS 30178 0001 K NJ CRUSH,other,KangaROOS 30178 0001 K NJ CRUSH / SNEAKER,KangaROOS 30178 0001 K NJ CRUSH
5464,[196989491301],40,SKECHERS,Beige,FaWoShSneakers,true,129600/ntpk skechers women shoes,129600/ntpk skechers women shoes,None,beige,...,129600/NTPK SKECHERS WOMEN SHOES/ MAX CUSHIONING,0020,NaN,NaN,medium,NaN,129600/NTPK SKECHERS WOMEN SHOES,other,129600/NTPK SKECHERS WOMEN SHOES/ MAX CUSHIONING,129600/NTPK SKECHERS WOMEN SHOES
5505,[197976260368],40,SKECHERS,Beige,FaWoShSneakers,true,177390 skechers shoes,177390 skechers shoes,None,black,...,177390 SKECHERS SHOES / TRES AIR,0020,NaN,NaN,medium,NaN,177390 SKECHERS SHOES,other,177390 SKECHERS SHOES / TRES AIR,177390 SKECHERS SHOES

In [33]:
#check if some name [el_CY] are missing
df_data["name [el_CY]"].isna().sum()

608

In [34]:
#check if some name [en_GB] are missing
df_data["name [en_GB]"].isna().sum() #no missing values

0

Given that `name [el_CY]` has missing values in some rows, while `name [en_GB]` not, we should only use the English name in the following grouping to provide more accurate results. 

A similar check for English and Greek descriptions.

In [35]:
#check if some shortDescription [el_CY] are missing
df_data["shortDescription [el_CY]"].isna().sum()

1336

In [36]:
#check if some shortDescription [en_GB] are missing
df_data["shortDescription [en_GB]"].isna().sum() #no missing values

0

Again, some Greek descriptions are missing, while there are no missing English descriptions. So it would be better to use only English.

In [37]:
# may adjust these to be more/less strict!
group_keys = [     
    'brand',
    'color',   
    'category',
    'name [en_GB]',
    'shortDescription [en_GB]'] # provided that short descriptions are the same, there is no need to include long descriptions


# Group and count occurrences
group_sizes_en = df_data.groupby(group_keys).size().reset_index(name='count')

# Filter groups that occur more than once
duplicates_en = group_sizes_en[group_sizes_en['count'] > 1]

# Get full rows that belong to these duplicate groups
identical_products_en = df_data.merge(duplicates_en[group_keys], on=group_keys, how='inner')

# Assign group IDs
identical_products_en['product_group_id'] = identical_products_en.groupby(group_keys).ngroup()

# Create separate DataFrames for each group
grouped_dict_en = {
    f"group_{group_id}": group_df.drop(columns="product_group_id")
    for group_id, group_df in identical_products_en.groupby("product_group_id")
}

# Preview first 5 groups with only group keys + product_group_id
for group_id, df in list(grouped_dict_en.items())[:5]:
    print(f"\n===== Group: {group_id} =====")
    print(df[group_keys])

===== Group: group_0 =====
      brand      color        category name [en_GB]  \
43   ADIDAS  Aluminium  FaMeShSneakers       Ozelle
127  ADIDAS  Aluminium  FaMeShSneakers       Ozelle

                              shortDescription [en_GB]
43   Regular fit<br>Lace closure<br>Textile upper<b...
127  Regular fit<br>Lace closure<br>Textile upper<b...

===== Group: group_1 =====
      brand  color        category name [en_GB]  \
89   ADIDAS  Beige  FaMeShSneakers   Adizero sl
334  ADIDAS  Beige  FaMeShSneakers   Adizero sl
581  ADIDAS  Beige  FaMeShSneakers   Adizero sl

                              shortDescription [en_GB]
89   <br>Lace closure for premium lockdown<br>Part ...
334  <br>Lace closure for premium lockdown<br>Part ...
581  <br>Lace closure for premium lockdown<br>Part ...

===== Group: group_2 =====
      brand  color        category          name [en_GB]  \
489  ADIDAS  Black  FaMeShSneakers  Adidas men alphaedge
692  ADIDAS  Black  FaMeShSneakers  Adidas men alphaedge

                              shortDescription [en_GB]
489  <html><body><p>The adidas AlphaEdge+ shoes com...
692  <html><body><p>The adidas AlphaEdge+ shoes com...

===== Group: group_3 =====
      brand  color        category         name [en_GB]  \
241  ADIDAS  Black  FaMeShSneakers  Adidas men galaxy 7
632  ADIDAS  Black  FaMeShSneakers  Adidas men galaxy 7
957  ADIDAS  Black  FaMeShSneakers  Adidas men galaxy 7

                              shortDescription [en_GB]
241  <html><body><p>Supportive running shoes with a...
632  <html><body><p>Supportive running shoes with a...
957  <html><body><p>Supportive running shoes with a...

===== Group: group_4 =====
      brand  color        category name [en_GB]  \
474  ADIDAS  Black  FaMeShSneakers   Adizero sl
534  ADIDAS  Black  FaMeShSneakers   Adizero sl

                              shortDescription [en_GB]
474  <br>Lace closure for premium lockdown<br>Part ...
534  <br>Lace closure for premium lockdown<br>Part ...

In [38]:
# add a column named 'task1_approach1' that has the group id for the current task and approach
df_data['task1_approach1'] = df_data.groupby(group_keys).ngroup()
df_data

,EAN,size,brand,color,category,returnable,name [el_CY],name [en_GB],updateOnDelta,refinementColor,...,shoeType,shoeShape,fashionMaterial,shoeWidth,heelHeight,name,heelType,longDescription,shortDescription,task1_approach1
0,[],44,ASICS,White / Black,FaMeShSneakers,true,Gel-rocket 11 mens volleyball/indoor shoes,Gel-rocket 11 mens volleyball/indoor shoes,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1041.0
1,[],44,VANS,Black,FaMeShSneakers,true,Mens filmore suede,Mens filmore suede,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4423.0
2,[],44.5,ADIDAS,NaN,FaMeShSneakers,true,Ih6003,Adidas response,NaN,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[],42,NIKE,White / Black / Volt,FaMeShSneakers,true,React vision worldwide mens,React vision worldwide mens,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2839.0
4,[],11/EU 46,PUMA,Black/white,FaMeShSneakers,true,Puma men's x-ray 3 sd,Puma men's x-ray 3 sd,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3168.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5818,[],37,BUFFALO,White / Silver / Black,FaWoShSneakers,true,Triple hollow sneakers,Triple hollow sneakers,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1132.0
5819,[],39,ADIDAS ORIGINALS,White,FaWoShSneakers,true,Adidas sambae w,Adidas sambae w,NaN,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,882.0
5820,[],41,GUESS,White,FaWoShSneakers,true,Elbina sneakers,Elbina sneakers,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1589.0
5821,[],36.5,NEW BALANCE,Cloud White / Burgundy,FaWoShSneakers,true,327 sportstyle sneakers,327 sportstyle sneakers,None,miscellaneous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2028.0
5822,[],37,NEW BALANCE,Cloud White / Burgundy,FaWoShSneakers,true,New balance 327 sportstyle sneakers,New balance 327 sportstyle sneakers,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029.0

In [39]:
# count products with empty group ids
df_data['task1_approach1'].isna().sum()

26

From the above output we observe that some products have not been grouped using Approach 1. Further exploration of these products:

In [40]:
#explore the products that have not been grouped
df_data[df_data['task1_approach1'].isna()].head()

,EAN,size,brand,color,category,returnable,name [el_CY],name [en_GB],updateOnDelta,refinementColor,...,shoeType,shoeShape,fashionMaterial,shoeWidth,heelHeight,name,heelType,longDescription,shortDescription,task1_approach1
2,[],44.5,ADIDAS,NaN,FaMeShSneakers,true,Ih6003,Adidas response,NaN,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,[],42,TALBOT SHOES,NaN,FaMeShSneakers,true,Joma men,Joma men,None,NaN,...,0090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402,[],46,TALBOT SHOES,NaN,FaMeShSneakers,true,Joma men,Joma men,None,NaN,...,0090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,[],45.5,ADIDAS,NaN,FaMeShSneakers,true,Id8760,Adidas galaxy 7,NaN,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
868,[],42.5,ON RUNNING,NaN,FaMeShSneakers,true,On running cloud 5,On running cloud 5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

From the above output we observe that, even though the products with indices 123 and 402 are the same, they have not been grouped together. I suspect that this might be due to having missing colors and Python might treat them as not having the same color. Let's investigate this assumption:

In [41]:
df_data.iloc[123,3] == df_data.iloc[402,3]

False

So the above verifies that the above assumption is true. Following, we group without considering colors to capture variants **(Task 2)**.

In [42]:
# Check number of grouped created
df_data["task1_approach1"].nunique()

4608

In [43]:
df_data.shape

(5823, 34)

Out of the 5823 records, **approach 1** created 4608 groups. This means that we grouped some products that are identical w.r.t. the previous fields. However very few groups were created.

## Task 2: Match similar products with different variants

#### **Approach 1:** Group products using existing fields

The idea is similar to that of **Task 1**. Here we remove `color` from group keys. This results in groups of identical products in the same/ different colors.

In [44]:
# may adjust these to be more/less strict!
group_keys = [
    'brand',
    'category',
    'name [en_GB]',
    'shortDescription [en_GB]']

# Group and count occurrences
group_sizes_en = df_data.groupby(group_keys).size().reset_index(name='count')

# Filter groups that occur more than once
duplicates_en = group_sizes_en[group_sizes_en['count'] > 1]

# Get full rows that belong to these duplicate groups
identical_products_en = df_data.merge(duplicates_en[group_keys], on=group_keys, how='inner')

# Assign group IDs
identical_products_en['product_group_id'] = identical_products_en.groupby(group_keys).ngroup()

# Create separate DataFrames for each group
grouped_dict_en = {
    f"group_{group_id}": group_df.drop(columns="product_group_id")
    for group_id, group_df in identical_products_en.groupby("product_group_id")
}

# Preview first 5 groups with only group keys + product_group_id
for group_id, df in list(grouped_dict_en.items())[:5]:
    print(f"\n===== Group: {group_id} =====")
    print(df[group_keys])

===== Group: group_0 =====
      brand        category name [en_GB]  \
233  ADIDAS  FaMeShSneakers  4dfwd 2 men
516  ADIDAS  FaMeShSneakers  4dfwd 2 men

                              shortDescription [en_GB]
233  <br>Lace closure<br>adidas PRIMEKNIT textile u...
516  <br>Lace closure<br>adidas PRIMEKNIT textile u...

===== Group: group_1 =====
      brand        category  name [en_GB]  \
179  ADIDAS  FaMeShSneakers  4dfwd 2 mens
521  ADIDAS  FaMeShSneakers  4dfwd 2 mens

                              shortDescription [en_GB]
179  <br>Lace closure<br>adidas PRIMEKNIT textile u...
521  <br>Lace closure<br>adidas PRIMEKNIT textile u...

===== Group: group_2 =====
       brand        category name [en_GB] shortDescription [en_GB]
207   ADIDAS  FaMeShSneakers  4dfwd 4 men              4DFWD 4 Men
312   ADIDAS  FaMeShSneakers  4dfwd 4 men              4DFWD 4 Men
866   ADIDAS  FaMeShSneakers  4dfwd 4 men              4DFWD 4 Men
1246  ADIDAS  FaMeShSneakers  4dfwd 4 men              4DFWD 4 Men

===== Group: group_3 =====
      brand        category          name [en_GB]  \
57   ADIDAS  FaMeShSneakers  Adidas alphaboost v1
813  ADIDAS  FaMeShSneakers  Adidas alphaboost v1

                              shortDescription [en_GB]
57   <html><body><p>ADIDAS AlphaBoost V1</p></body>...
813  <html><body><p>ADIDAS AlphaBoost V1</p></body>...

===== Group: group_4 =====
      brand        category                                     name [en_GB]  \
142  ADIDAS  FaMeShSneakers  Adidas bounce legends      carbon/goldmt/cblack
881  ADIDAS  FaMeShSneakers  Adidas bounce legends      carbon/goldmt/cblack

                              shortDescription [en_GB]
142  <html><body><p>ADIDAS Bounce Legends      CARB...
881  <html><body><p>ADIDAS Bounce Legends      CARB...

In [45]:
# add a column with the group id
df_data['task2_approach1'] = df_data.groupby(group_keys).ngroup()
df_data

,EAN,size,brand,color,category,returnable,name [el_CY],name [en_GB],updateOnDelta,refinementColor,...,shoeShape,fashionMaterial,shoeWidth,heelHeight,name,heelType,longDescription,shortDescription,task1_approach1,task2_approach1
0,[],44,ASICS,White / Black,FaMeShSneakers,true,Gel-rocket 11 mens volleyball/indoor shoes,Gel-rocket 11 mens volleyball/indoor shoes,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1041.0,843.0
1,[],44,VANS,Black,FaMeShSneakers,true,Mens filmore suede,Mens filmore suede,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4423.0,3737.0
2,[],44.5,ADIDAS,NaN,FaMeShSneakers,true,Ih6003,Adidas response,NaN,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0
3,[],42,NIKE,White / Black / Volt,FaMeShSneakers,true,React vision worldwide mens,React vision worldwide mens,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2839.0,2099.0
4,[],11/EU 46,PUMA,Black/white,FaMeShSneakers,true,Puma men's x-ray 3 sd,Puma men's x-ray 3 sd,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3168.0,2609.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5818,[],37,BUFFALO,White / Silver / Black,FaWoShSneakers,true,Triple hollow sneakers,Triple hollow sneakers,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1132.0,933.0
5819,[],39,ADIDAS ORIGINALS,White,FaWoShSneakers,true,Adidas sambae w,Adidas sambae w,NaN,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,882.0,681.0
5820,[],41,GUESS,White,FaWoShSneakers,true,Elbina sneakers,Elbina sneakers,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1589.0,1332.0
5821,[],36.5,NEW BALANCE,Cloud White / Burgundy,FaWoShSneakers,true,327 sportstyle sneakers,327 sportstyle sneakers,None,miscellaneous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2028.0,1755.0
5822,[],37,NEW BALANCE,Cloud White / Burgundy,FaWoShSneakers,true,New balance 327 sportstyle sneakers,New balance 327 sportstyle sneakers,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029.0,1800.0

In [46]:
# investigate for products with missing group
df_data['task2_approach1'].isna().sum()

11

Again, some products were not grouped. Further investigate them:

In [47]:
#explore the products that have not been grouped
df_data[df_data['task2_approach1'].isna()].head()

,EAN,size,brand,color,category,returnable,name [el_CY],name [en_GB],updateOnDelta,refinementColor,...,shoeShape,fashionMaterial,shoeWidth,heelHeight,name,heelType,longDescription,shortDescription,task1_approach1,task2_approach1
1075,[],45,NaN,Black,FaMeShSneakers,true,C8979,C8979,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2258,[],43,NaN,All White,FaMeShSneakers,true,C8979,C8979,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2559,[],40,NaN,Black,FaMeShSneakers,true,C8979,C8979,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2941,[],39,NaN,White,FaWoShSneakers,true,C895,C895,None,white,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3856,[],36,NaN,Black,FaWoShSneakers,true,C895,C895,None,black,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
# Check number of grouped created
df_data["task2_approach1"].nunique()

3900

From the above output we observe that products 1075, 2258, 2559 are the same (with different color) but were not grouped. The issue is that brand is missing so they could not be grouped.  
**Problem that we observe with Approach 1 (in both tasks):** Some products, despite being identical/variants, fail to be grouped. This is because some fields (that are used in grouping) contain missing values. However this corresponds to only a few cases and it can be fixed manually, or we could be less strict and group only based on fields with no missing values.   

The following approaches reveal that additional products can be grouped together. Therefore, we do not proceed with further exploration of approach 1.

**Approach 1** is the naive approach and doesn't require any evaluation: products that were grouped are indeed identical (task 1) or variants (task 2). Following, we explore some other approaches including image and language processing.